### ISSUE TITLE
ncs_mdes does not work on JRuby

### ISSUE THREAD

**Issue by rsutphin** [NUARIG/ncs_mdes#5]
Several specs fail under JRuby 1.6.4. All of them appear to be related to extracting namespaced attribute values, so I'm guessing it's an incompatibility with Nokogiri. Determine who's at fault and fix it.

```
/var/lib/hudson/runner-home/.rvm/rubies/jruby-1.6.4/bin/jruby -S bundle exec rspec spec/ncs_navigator/mdes_spec.rb spec/ncs_navigator/mdes/source_documents_spec.rb spec/ncs_navigator/mdes/transmission_table_spec.rb spec/ncs_navigator/mdes/variable_type_spec.rb spec/ncs_navigator/mdes/variable_spec.rb spec/ncs_navigator/mdes/specification_spec.rb spec/ncs_navigator/mdes/version_spec.rb
............................................F.......FFF.......................FFFF.FFFFF................................................................................................

Failures:

 1) NcsNavigator::Mdes::VariableType.from_xsd_simple_type#code_list when there are enumerated values has the description
    Failure/Error: subject.code_list.description.should == "Eq"
      expected: "Eq"
           got: nil (using ==)
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_type_spec.rb:119:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'

 2) NcsNavigator::Mdes::VariableType::CodeListEntry.from_xsd_enumeration#label is set
    Failure/Error: missing.label.should == "Missing in Error"
      expected: "Missing in Error"
           got: nil (using ==)
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_type_spec.rb:179:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'

 3) NcsNavigator::Mdes::VariableType::CodeListEntry.from_xsd_enumeration#global_value is set
    Failure/Error: missing.global_value.should == '99-4'
      expected: "99-4"
           got: nil (using ==)
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_type_spec.rb:185:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'

 4) NcsNavigator::Mdes::VariableType::CodeListEntry.from_xsd_enumeration#master_cl is set
    Failure/Error: missing.master_cl.should == 'missing_data'
      expected: "missing_data"
           got: nil (using ==)
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_type_spec.rb:191:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'

 5) NcsNavigator::Mdes::Variable.from_element#pii is false when blank
    Failure/Error: variable('<xs:element ncsdoc:pii=""/>').pii.should == false
      expected: false
           got: :unknown (using ==)
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_spec.rb:140:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'

 6) NcsNavigator::Mdes::Variable.from_element#pii is true when "Y"
    Failure/Error: variable('<xs:element ncsdoc:pii="Y"/>').pii.should == true
      expected: true
           got: :unknown (using ==)
      Diff:
      @@ -1,2 +1,2 @@
      -true
      +:unknown
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_spec.rb:144:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'

 7) NcsNavigator::Mdes::Variable.from_element#pii is :possible when "P"
    Failure/Error: variable('<xs:element ncsdoc:pii="P"/>').pii.should == :possible
      expected: :possible
           got: :unknown (using ==)
      Diff:
      @@ -1,2 +1,2 @@
      -:possible
      +:unknown
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_spec.rb:148:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'

 8) NcsNavigator::Mdes::Variable.from_element#pii is the literal value when some other value
    Failure/Error: variable('<xs:element ncsdoc:pii="7"/>').pii.should == '7'
      expected: "7"
           got: :unknown (using ==)
      Diff:
      @@ -1,2 +1,2 @@
      -7
      +:unknown
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_spec.rb:152:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'

 9) NcsNavigator::Mdes::Variable.from_element#status is :active for 1
    Failure/Error: variable('<xs:element ncsdoc:status="1"/>').status.should == :active
      expected: :active
           got: nil (using ==)
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_spec.rb:162:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'

 10) NcsNavigator::Mdes::Variable.from_element#status is :new for 2
    Failure/Error: variable('<xs:element ncsdoc:status="2"/>').status.should == :new
      expected: :new
           got: nil (using ==)
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_spec.rb:166:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'

 11) NcsNavigator::Mdes::Variable.from_element#status is :modified for 3
    Failure/Error: variable('<xs:element ncsdoc:status="3"/>').status.should == :modified
      expected: :modified
           got: nil (using ==)
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_spec.rb:170:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'

 12) NcsNavigator::Mdes::Variable.from_element#status is :retired for 4
    Failure/Error: variable('<xs:element ncsdoc:status="4"/>').status.should == :retired
      expected: :retired
           got: nil (using ==)
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_spec.rb:174:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'

 13) NcsNavigator::Mdes::Variable.from_element#status is the literal value for some other value
    Failure/Error: variable('<xs:element ncsdoc:status="P4"/>').status.should == 'P4'
      expected: "P4"
           got: nil (using ==)
    # org/jruby/RubyProc.java:274:in `call'
    # ./spec/ncs_navigator/mdes/variable_spec.rb:178:in `Mdes'
    # org/jruby/RubyKernel.java:2061:in `instance_eval'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
    # org/jruby/RubyArray.java:2336:in `collect'
```

When it is working, enable JRuby in the [CI build](https://public-ci.nubic.northwestern.edu/job/ncs_mdes).
